apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: expense
spec:
  clusterIP: None # <= Don't forget!! for headless service there is n cluster ip
  selector:
    projectname: expense
    component: mysql
    tier: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    projectname: expense
    component: mysql
    tier: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306 
---
           