apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: expense
spec:
  clusterIP: None # <= Don't forget!! for headless service there is n cluster ip
  selector:
    projectname: expense
    component: mysql
    tier: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    projectname: expense
    component: mysql
    tier: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306 
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    matchLabels:
      project: expense # has to match .spec.template.metadata.labels
      component: mysql
      tier: db
  serviceName: "mysql-headless"  # this is the headless service should be mentiond for statefulset
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        project: expense # has to match .spec.selector.matchLabels
        component: mysql
        tier: db
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:v1
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  # this is pvc definition, directly mentioned here        
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "expense-ebs"
      resources:
        requests:
          storage: 1Gi           